language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet tool install --global dotnet-sonarscanner --version 4.6.0

before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"

stages:
  - compile
  - test
  - name: deploy
    if: branch = master OR branch = development

jobs:
  include:
    - stage: compile
      script:
        - dotnet restore
        - dotnet build

    - stage: test
      script:
        - dotnet test IamService/Iam.Tests/Iam.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        - dotnet sonarscanner begin /k:"MF" /d:sonar.host.url=https://sonarcloud.io /d:sonar.organization="my-finances" /d:sonar.login="b8de6fc2e0fd00bc0b30a3f9ee84a1948a1fc580" /d:sonar.cs.opencover.reportsPaths="IamService/Iam.Tests/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs"
        - dotnet build
        - dotnet sonarscanner end /d:sonar.login="89e81ebd21fafc07ddba09ca2b1a76d5aeb528b6"






