language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

stages:
  - compile
  - test
  - name: deploy
    if: branch = master OR branch = development

jobs:
  include:
    - stage: compile
      script: dotnet restore
    - script: dotnet build
  
